/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishedAt' : IDL.Int,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const BookFormat = IDL.Variant({
  'paperback' : IDL.Text,
  'kindle' : IDL.Text,
});
export const Book = IDL.Record({
  'id' : IDL.Text,
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'audiobookLink' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'genre' : IDL.Text,
  'formats' : IDL.Vec(BookFormat),
});
export const CustomerAddress = IDL.Record({
  'id' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'fullName' : IDL.Text,
  'line1' : IDL.Text,
  'line2' : IDL.Text,
  'state' : IDL.Text,
  'addressLabel' : IDL.Text,
  'isDefault' : IDL.Bool,
  'customerId' : IDL.Text,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const Review = IDL.Record({
  'bookId' : IDL.Text,
  'reviewerName' : IDL.Text,
  'email' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const Audiobook = IDL.Record({
  'id' : IDL.Text,
  'duration' : IDL.Text,
  'coverEmoji' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'razorpayUrlINR' : IDL.Text,
  'razorpayUrlUSD' : IDL.Text,
  'priceINR' : IDL.Nat,
  'priceUSD' : IDL.Nat,
  'narrator' : IDL.Text,
});
export const Coupon = IDL.Record({
  'discountValue' : IDL.Nat,
  'expiryDate' : IDL.Int,
  'code' : IDL.Text,
  'discountType' : IDL.Text,
  'usageCount' : IDL.Nat,
  'isActive' : IDL.Bool,
  'maxUsages' : IDL.Nat,
  'currency' : IDL.Text,
});
export const MerchItem = IDL.Record({
  'id' : IDL.Text,
  'razorpayUrl' : IDL.Text,
  'coverEmoji' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'category' : IDL.Text,
  'priceINR' : IDL.Nat,
  'priceUSD' : IDL.Nat,
});
export const ShippingAddress = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
  'fullName' : IDL.Text,
  'line1' : IDL.Text,
  'line2' : IDL.Text,
  'state' : IDL.Text,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'productId' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'razorpayPaymentId' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'customerPhone' : IDL.Text,
  'createdAt' : IDL.Int,
  'totalAmount' : IDL.Nat,
  'currency' : IDL.Text,
  'notes' : IDL.Text,
  'shippingAddress' : IDL.Opt(ShippingAddress),
  'customerId' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(OrderItem),
  'customerEmail' : IDL.Text,
});
export const Setting = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
export const CustomerAccount = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'passwordHash' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addBlogPost' : IDL.Func([BlogPost], [], []),
  'addBook' : IDL.Func([Book], [], []),
  'addCustomerAddress' : IDL.Func([CustomerAddress], [], []),
  'addReview' : IDL.Func([Review], [], []),
  'addSubscriber' : IDL.Func([IDL.Text], [], []),
  'changeCustomerPassword' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'createAudiobook' : IDL.Func([Audiobook], [], []),
  'createCoupon' : IDL.Func([Coupon], [], []),
  'createMerchItem' : IDL.Func([MerchItem], [], []),
  'createOrder' : IDL.Func([Order], [], []),
  'deleteAudiobook' : IDL.Func([IDL.Text], [], []),
  'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
  'deleteBook' : IDL.Func([IDL.Text], [], []),
  'deleteCoupon' : IDL.Func([IDL.Text], [], []),
  'deleteCustomerAddress' : IDL.Func([IDL.Text], [], []),
  'deleteMerchItem' : IDL.Func([IDL.Text], [], []),
  'deleteOrder' : IDL.Func([IDL.Text], [], []),
  'getAllSettings' : IDL.Func([], [IDL.Vec(Setting)], ['query']),
  'getAudiobook' : IDL.Func([IDL.Text], [IDL.Opt(Audiobook)], ['query']),
  'getAudiobooks' : IDL.Func([], [IDL.Vec(Audiobook)], ['query']),
  'getAuthorBio' : IDL.Func([], [IDL.Text], ['query']),
  'getBlogPost' : IDL.Func([IDL.Text], [BlogPost], ['query']),
  'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getBook' : IDL.Func([IDL.Text], [Book], ['query']),
  'getBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getCoupon' : IDL.Func([IDL.Text], [IDL.Opt(Coupon)], ['query']),
  'getCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
  'getCustomer' : IDL.Func([IDL.Text], [IDL.Opt(CustomerAccount)], ['query']),
  'getCustomerAddresses' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CustomerAddress)],
      ['query'],
    ),
  'getMerchItem' : IDL.Func([IDL.Text], [IDL.Opt(MerchItem)], ['query']),
  'getMerchItems' : IDL.Func([], [IDL.Vec(MerchItem)], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'getSetting' : IDL.Func([IDL.Text], [IDL.Opt(Setting)], ['query']),
  'getSubscribers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'incrementCouponUsage' : IDL.Func([IDL.Text], [], []),
  'loginCustomer' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(CustomerAccount)],
      [],
    ),
  'registerCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Text)],
      [],
    ),
  'removeSubscriber' : IDL.Func([IDL.Text], [], []),
  'setDefaultAddress' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateAudiobook' : IDL.Func([Audiobook], [], []),
  'updateAuthorBio' : IDL.Func([IDL.Text], [], []),
  'updateBlogPost' : IDL.Func([BlogPost], [], []),
  'updateBook' : IDL.Func([Book], [], []),
  'updateCustomer' : IDL.Func([CustomerAccount], [], []),
  'updateCustomerAddress' : IDL.Func([CustomerAddress], [], []),
  'updateMerchItem' : IDL.Func([MerchItem], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateSetting' : IDL.Func([Setting], [], []),
  'validateCoupon' : IDL.Func([IDL.Text], [IDL.Opt(Coupon)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishedAt' : IDL.Int,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const BookFormat = IDL.Variant({
    'paperback' : IDL.Text,
    'kindle' : IDL.Text,
  });
  const Book = IDL.Record({
    'id' : IDL.Text,
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'audiobookLink' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'genre' : IDL.Text,
    'formats' : IDL.Vec(BookFormat),
  });
  const CustomerAddress = IDL.Record({
    'id' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'fullName' : IDL.Text,
    'line1' : IDL.Text,
    'line2' : IDL.Text,
    'state' : IDL.Text,
    'addressLabel' : IDL.Text,
    'isDefault' : IDL.Bool,
    'customerId' : IDL.Text,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const Review = IDL.Record({
    'bookId' : IDL.Text,
    'reviewerName' : IDL.Text,
    'email' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const Audiobook = IDL.Record({
    'id' : IDL.Text,
    'duration' : IDL.Text,
    'coverEmoji' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'razorpayUrlINR' : IDL.Text,
    'razorpayUrlUSD' : IDL.Text,
    'priceINR' : IDL.Nat,
    'priceUSD' : IDL.Nat,
    'narrator' : IDL.Text,
  });
  const Coupon = IDL.Record({
    'discountValue' : IDL.Nat,
    'expiryDate' : IDL.Int,
    'code' : IDL.Text,
    'discountType' : IDL.Text,
    'usageCount' : IDL.Nat,
    'isActive' : IDL.Bool,
    'maxUsages' : IDL.Nat,
    'currency' : IDL.Text,
  });
  const MerchItem = IDL.Record({
    'id' : IDL.Text,
    'razorpayUrl' : IDL.Text,
    'coverEmoji' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'category' : IDL.Text,
    'priceINR' : IDL.Nat,
    'priceUSD' : IDL.Nat,
  });
  const ShippingAddress = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'fullName' : IDL.Text,
    'line1' : IDL.Text,
    'line2' : IDL.Text,
    'state' : IDL.Text,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'productId' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'razorpayPaymentId' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'customerPhone' : IDL.Text,
    'createdAt' : IDL.Int,
    'totalAmount' : IDL.Nat,
    'currency' : IDL.Text,
    'notes' : IDL.Text,
    'shippingAddress' : IDL.Opt(ShippingAddress),
    'customerId' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(OrderItem),
    'customerEmail' : IDL.Text,
  });
  const Setting = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
  const CustomerAccount = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'passwordHash' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addBlogPost' : IDL.Func([BlogPost], [], []),
    'addBook' : IDL.Func([Book], [], []),
    'addCustomerAddress' : IDL.Func([CustomerAddress], [], []),
    'addReview' : IDL.Func([Review], [], []),
    'addSubscriber' : IDL.Func([IDL.Text], [], []),
    'changeCustomerPassword' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'createAudiobook' : IDL.Func([Audiobook], [], []),
    'createCoupon' : IDL.Func([Coupon], [], []),
    'createMerchItem' : IDL.Func([MerchItem], [], []),
    'createOrder' : IDL.Func([Order], [], []),
    'deleteAudiobook' : IDL.Func([IDL.Text], [], []),
    'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
    'deleteBook' : IDL.Func([IDL.Text], [], []),
    'deleteCoupon' : IDL.Func([IDL.Text], [], []),
    'deleteCustomerAddress' : IDL.Func([IDL.Text], [], []),
    'deleteMerchItem' : IDL.Func([IDL.Text], [], []),
    'deleteOrder' : IDL.Func([IDL.Text], [], []),
    'getAllSettings' : IDL.Func([], [IDL.Vec(Setting)], ['query']),
    'getAudiobook' : IDL.Func([IDL.Text], [IDL.Opt(Audiobook)], ['query']),
    'getAudiobooks' : IDL.Func([], [IDL.Vec(Audiobook)], ['query']),
    'getAuthorBio' : IDL.Func([], [IDL.Text], ['query']),
    'getBlogPost' : IDL.Func([IDL.Text], [BlogPost], ['query']),
    'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getBook' : IDL.Func([IDL.Text], [Book], ['query']),
    'getBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getCoupon' : IDL.Func([IDL.Text], [IDL.Opt(Coupon)], ['query']),
    'getCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
    'getCustomer' : IDL.Func([IDL.Text], [IDL.Opt(CustomerAccount)], ['query']),
    'getCustomerAddresses' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CustomerAddress)],
        ['query'],
      ),
    'getMerchItem' : IDL.Func([IDL.Text], [IDL.Opt(MerchItem)], ['query']),
    'getMerchItems' : IDL.Func([], [IDL.Vec(MerchItem)], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
    'getSetting' : IDL.Func([IDL.Text], [IDL.Opt(Setting)], ['query']),
    'getSubscribers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'incrementCouponUsage' : IDL.Func([IDL.Text], [], []),
    'loginCustomer' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(CustomerAccount)],
        [],
      ),
    'registerCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Text)],
        [],
      ),
    'removeSubscriber' : IDL.Func([IDL.Text], [], []),
    'setDefaultAddress' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateAudiobook' : IDL.Func([Audiobook], [], []),
    'updateAuthorBio' : IDL.Func([IDL.Text], [], []),
    'updateBlogPost' : IDL.Func([BlogPost], [], []),
    'updateBook' : IDL.Func([Book], [], []),
    'updateCustomer' : IDL.Func([CustomerAccount], [], []),
    'updateCustomerAddress' : IDL.Func([CustomerAddress], [], []),
    'updateMerchItem' : IDL.Func([MerchItem], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateSetting' : IDL.Func([Setting], [], []),
    'validateCoupon' : IDL.Func([IDL.Text], [IDL.Opt(Coupon)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };