/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BlogPost {
    id: string;
    coverImageUrl: string;
    title: string;
    content: string;
    publishedAt: bigint;
    excerpt: string;
    category: string;
}
export interface Coupon {
    discountValue: bigint;
    expiryDate: bigint;
    code: string;
    discountType: string;
    usageCount: bigint;
    isActive: boolean;
    maxUsages: bigint;
    currency: string;
}
export interface ShippingAddress {
    country: string;
    city: string;
    fullName: string;
    line1: string;
    line2: string;
    state: string;
    phone: string;
    pincode: string;
}
export interface Book {
    id: string;
    coverImageUrl: string;
    title: string;
    featured: boolean;
    audiobookLink?: string;
    description: string;
    genre: string;
    formats: Array<BookFormat>;
}
export interface OrderItem {
    name: string;
    productId: string;
    currency: string;
    quantity: bigint;
    price: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Order {
    id: string;
    razorpayPaymentId: string;
    customerName: string;
    status: string;
    customerPhone: string;
    createdAt: bigint;
    totalAmount: bigint;
    currency: string;
    notes: string;
    shippingAddress?: ShippingAddress;
    customerId?: string;
    items: Array<OrderItem>;
    customerEmail: string;
}
export interface MerchItem {
    id: string;
    razorpayUrl: string;
    coverEmoji: string;
    name: string;
    description: string;
    isActive: boolean;
    category: string;
    priceINR: bigint;
    priceUSD: bigint;
}
export interface Audiobook {
    id: string;
    duration: string;
    coverEmoji: string;
    name: string;
    description: string;
    isActive: boolean;
    razorpayUrlINR: string;
    razorpayUrlUSD: string;
    priceINR: bigint;
    priceUSD: bigint;
    narrator: string;
}
export type BookFormat = {
    __kind__: "paperback";
    paperback: string;
} | {
    __kind__: "kindle";
    kindle: string;
};
export interface CustomerAccount {
    id: string;
    name: string;
    createdAt: bigint;
    email: string;
    passwordHash: string;
}
export interface Setting {
    key: string;
    value: string;
}
export interface CustomerAddress {
    id: string;
    country: string;
    city: string;
    fullName: string;
    line1: string;
    line2: string;
    state: string;
    addressLabel: string;
    isDefault: boolean;
    customerId: string;
    phone: string;
    pincode: string;
}
export interface Review {
    bookId: string;
    reviewerName: string;
    email: string;
    comment: string;
    rating: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addBlogPost(post: BlogPost): Promise<void>;
    addBook(book: Book): Promise<void>;
    addCustomerAddress(address: CustomerAddress): Promise<void>;
    addReview(review: Review): Promise<void>;
    addSubscriber(email: string): Promise<void>;
    changeCustomerPassword(id: string, oldHash: string, newHash: string): Promise<boolean>;
    createAudiobook(audiobook: Audiobook): Promise<void>;
    createCoupon(coupon: Coupon): Promise<void>;
    createMerchItem(merchItem: MerchItem): Promise<void>;
    createOrder(order: Order): Promise<void>;
    deleteAudiobook(id: string): Promise<void>;
    deleteBlogPost(id: string): Promise<void>;
    deleteBook(id: string): Promise<void>;
    deleteCoupon(code: string): Promise<void>;
    deleteCustomerAddress(id: string): Promise<void>;
    deleteMerchItem(id: string): Promise<void>;
    deleteOrder(id: string): Promise<void>;
    getAllSettings(): Promise<Array<Setting>>;
    getAudiobook(id: string): Promise<Audiobook | null>;
    getAudiobooks(): Promise<Array<Audiobook>>;
    getAuthorBio(): Promise<string>;
    getBlogPost(id: string): Promise<BlogPost>;
    getBlogPosts(): Promise<Array<BlogPost>>;
    getBook(id: string): Promise<Book>;
    getBooks(): Promise<Array<Book>>;
    getCoupon(code: string): Promise<Coupon | null>;
    getCoupons(): Promise<Array<Coupon>>;
    getCustomer(id: string): Promise<CustomerAccount | null>;
    getCustomerAddresses(customerId: string): Promise<Array<CustomerAddress>>;
    getMerchItem(id: string): Promise<MerchItem | null>;
    getMerchItems(): Promise<Array<MerchItem>>;
    getOrder(id: string): Promise<Order | null>;
    getOrders(): Promise<Array<Order>>;
    getReviews(bookId: string): Promise<Array<Review>>;
    getSetting(key: string): Promise<Setting | null>;
    getSubscribers(): Promise<Array<string>>;
    incrementCouponUsage(code: string): Promise<void>;
    loginCustomer(email: string, passwordHash: string): Promise<CustomerAccount | null>;
    registerCustomer(name: string, email: string, passwordHash: string): Promise<string | null>;
    removeSubscriber(email: string): Promise<void>;
    setDefaultAddress(customerId: string, addressId: string): Promise<void>;
    updateAudiobook(audiobook: Audiobook): Promise<void>;
    updateAuthorBio(bio: string): Promise<void>;
    updateBlogPost(post: BlogPost): Promise<void>;
    updateBook(book: Book): Promise<void>;
    updateCustomer(account: CustomerAccount): Promise<void>;
    updateCustomerAddress(address: CustomerAddress): Promise<void>;
    updateMerchItem(merchItem: MerchItem): Promise<void>;
    updateOrderStatus(id: string, status: string): Promise<void>;
    updateSetting(setting: Setting): Promise<void>;
    validateCoupon(code: string): Promise<Coupon | null>;
}
import type { Audiobook as _Audiobook, Book as _Book, BookFormat as _BookFormat, Coupon as _Coupon, CustomerAccount as _CustomerAccount, MerchItem as _MerchItem, Order as _Order, OrderItem as _OrderItem, Setting as _Setting, ShippingAddress as _ShippingAddress, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addBlogPost(arg0: BlogPost): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBlogPost(arg0);
            return result;
        }
    }
    async addBook(arg0: Book): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBook(to_candid_Book_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBook(to_candid_Book_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addCustomerAddress(arg0: CustomerAddress): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomerAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomerAddress(arg0);
            return result;
        }
    }
    async addReview(arg0: Review): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0);
            return result;
        }
    }
    async addSubscriber(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSubscriber(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSubscriber(arg0);
            return result;
        }
    }
    async changeCustomerPassword(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.changeCustomerPassword(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeCustomerPassword(arg0, arg1, arg2);
            return result;
        }
    }
    async createAudiobook(arg0: Audiobook): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAudiobook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAudiobook(arg0);
            return result;
        }
    }
    async createCoupon(arg0: Coupon): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCoupon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCoupon(arg0);
            return result;
        }
    }
    async createMerchItem(arg0: MerchItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMerchItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMerchItem(arg0);
            return result;
        }
    }
    async createOrder(arg0: Order): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(to_candid_Order_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(to_candid_Order_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteAudiobook(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAudiobook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAudiobook(arg0);
            return result;
        }
    }
    async deleteBlogPost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return result;
        }
    }
    async deleteBook(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBook(arg0);
            return result;
        }
    }
    async deleteCoupon(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCoupon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCoupon(arg0);
            return result;
        }
    }
    async deleteCustomerAddress(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomerAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomerAddress(arg0);
            return result;
        }
    }
    async deleteMerchItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMerchItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMerchItem(arg0);
            return result;
        }
    }
    async deleteOrder(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOrder(arg0);
            return result;
        }
    }
    async getAllSettings(): Promise<Array<Setting>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSettings();
            return result;
        }
    }
    async getAudiobook(arg0: string): Promise<Audiobook | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAudiobook(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAudiobook(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAudiobooks(): Promise<Array<Audiobook>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAudiobooks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAudiobooks();
            return result;
        }
    }
    async getAuthorBio(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuthorBio();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuthorBio();
            return result;
        }
    }
    async getBlogPost(arg0: string): Promise<BlogPost> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPost(arg0);
            return result;
        }
    }
    async getBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPosts();
            return result;
        }
    }
    async getBook(arg0: string): Promise<Book> {
        if (this.processError) {
            try {
                const result = await this.actor.getBook(arg0);
                return from_candid_Book_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBook(arg0);
            return from_candid_Book_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBooks(): Promise<Array<Book>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooks();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooks();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoupon(arg0: string): Promise<Coupon | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoupon(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoupon(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoupons(): Promise<Array<Coupon>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoupons();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoupons();
            return result;
        }
    }
    async getCustomer(arg0: string): Promise<CustomerAccount | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerAddresses(arg0: string): Promise<Array<CustomerAddress>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerAddresses(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerAddresses(arg0);
            return result;
        }
    }
    async getMerchItem(arg0: string): Promise<MerchItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMerchItem(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMerchItem(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMerchItems(): Promise<Array<MerchItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMerchItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMerchItems();
            return result;
        }
    }
    async getOrder(arg0: string): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviews(arg0: string): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviews(arg0);
            return result;
        }
    }
    async getSetting(arg0: string): Promise<Setting | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSetting(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSetting(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubscribers(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscribers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscribers();
            return result;
        }
    }
    async incrementCouponUsage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementCouponUsage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementCouponUsage(arg0);
            return result;
        }
    }
    async loginCustomer(arg0: string, arg1: string): Promise<CustomerAccount | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loginCustomer(arg0, arg1);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginCustomer(arg0, arg1);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerCustomer(arg0: string, arg1: string, arg2: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCustomer(arg0, arg1, arg2);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCustomer(arg0, arg1, arg2);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeSubscriber(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeSubscriber(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeSubscriber(arg0);
            return result;
        }
    }
    async setDefaultAddress(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDefaultAddress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDefaultAddress(arg0, arg1);
            return result;
        }
    }
    async updateAudiobook(arg0: Audiobook): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAudiobook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAudiobook(arg0);
            return result;
        }
    }
    async updateAuthorBio(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAuthorBio(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAuthorBio(arg0);
            return result;
        }
    }
    async updateBlogPost(arg0: BlogPost): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogPost(arg0);
            return result;
        }
    }
    async updateBook(arg0: Book): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBook(to_candid_Book_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBook(to_candid_Book_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateCustomer(arg0: CustomerAccount): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0);
            return result;
        }
    }
    async updateCustomerAddress(arg0: CustomerAddress): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomerAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomerAddress(arg0);
            return result;
        }
    }
    async updateMerchItem(arg0: MerchItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMerchItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMerchItem(arg0);
            return result;
        }
    }
    async updateOrderStatus(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, arg1);
            return result;
        }
    }
    async updateSetting(arg0: Setting): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSetting(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSetting(arg0);
            return result;
        }
    }
    async validateCoupon(arg0: string): Promise<Coupon | null> {
        if (this.processError) {
            try {
                const result = await this.actor.validateCoupon(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateCoupon(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BookFormat_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookFormat): BookFormat {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Book_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Book): Book {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Audiobook]): Audiobook | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Coupon]): Coupon | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomerAccount]): CustomerAccount | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MerchItem]): MerchItem | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ShippingAddress]): ShippingAddress | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Setting]): Setting | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    coverImageUrl: string;
    title: string;
    featured: boolean;
    audiobookLink: [] | [string];
    description: string;
    genre: string;
    formats: Array<_BookFormat>;
}): {
    id: string;
    coverImageUrl: string;
    title: string;
    featured: boolean;
    audiobookLink?: string;
    description: string;
    genre: string;
    formats: Array<BookFormat>;
} {
    return {
        id: value.id,
        coverImageUrl: value.coverImageUrl,
        title: value.title,
        featured: value.featured,
        audiobookLink: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.audiobookLink)),
        description: value.description,
        genre: value.genre,
        formats: from_candid_vec_n19(_uploadFile, _downloadFile, value.formats)
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    razorpayPaymentId: string;
    customerName: string;
    status: string;
    customerPhone: string;
    createdAt: bigint;
    totalAmount: bigint;
    currency: string;
    notes: string;
    shippingAddress: [] | [_ShippingAddress];
    customerId: [] | [string];
    items: Array<_OrderItem>;
    customerEmail: string;
}): {
    id: string;
    razorpayPaymentId: string;
    customerName: string;
    status: string;
    customerPhone: string;
    createdAt: bigint;
    totalAmount: bigint;
    currency: string;
    notes: string;
    shippingAddress?: ShippingAddress;
    customerId?: string;
    items: Array<OrderItem>;
    customerEmail: string;
} {
    return {
        id: value.id,
        razorpayPaymentId: value.razorpayPaymentId,
        customerName: value.customerName,
        status: value.status,
        customerPhone: value.customerPhone,
        createdAt: value.createdAt,
        totalAmount: value.totalAmount,
        currency: value.currency,
        notes: value.notes,
        shippingAddress: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.shippingAddress)),
        customerId: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.customerId)),
        items: value.items,
        customerEmail: value.customerEmail
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paperback: string;
} | {
    kindle: string;
}): {
    __kind__: "paperback";
    paperback: string;
} | {
    __kind__: "kindle";
    kindle: string;
} {
    return "paperback" in value ? {
        __kind__: "paperback",
        paperback: value.paperback
    } : "kindle" in value ? {
        __kind__: "kindle",
        kindle: value.kindle
    } : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BookFormat>): Array<BookFormat> {
    return value.map((x)=>from_candid_BookFormat_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Book>): Array<Book> {
    return value.map((x)=>from_candid_Book_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n27(_uploadFile, _downloadFile, x));
}
function to_candid_BookFormat_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookFormat): _BookFormat {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Book_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Book): _Book {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Order_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Order): _Order {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    razorpayPaymentId: string;
    customerName: string;
    status: string;
    customerPhone: string;
    createdAt: bigint;
    totalAmount: bigint;
    currency: string;
    notes: string;
    shippingAddress?: ShippingAddress;
    customerId?: string;
    items: Array<OrderItem>;
    customerEmail: string;
}): {
    id: string;
    razorpayPaymentId: string;
    customerName: string;
    status: string;
    customerPhone: string;
    createdAt: bigint;
    totalAmount: bigint;
    currency: string;
    notes: string;
    shippingAddress: [] | [_ShippingAddress];
    customerId: [] | [string];
    items: Array<_OrderItem>;
    customerEmail: string;
} {
    return {
        id: value.id,
        razorpayPaymentId: value.razorpayPaymentId,
        customerName: value.customerName,
        status: value.status,
        customerPhone: value.customerPhone,
        createdAt: value.createdAt,
        totalAmount: value.totalAmount,
        currency: value.currency,
        notes: value.notes,
        shippingAddress: value.shippingAddress ? candid_some(value.shippingAddress) : candid_none(),
        customerId: value.customerId ? candid_some(value.customerId) : candid_none(),
        items: value.items,
        customerEmail: value.customerEmail
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    coverImageUrl: string;
    title: string;
    featured: boolean;
    audiobookLink?: string;
    description: string;
    genre: string;
    formats: Array<BookFormat>;
}): {
    id: string;
    coverImageUrl: string;
    title: string;
    featured: boolean;
    audiobookLink: [] | [string];
    description: string;
    genre: string;
    formats: Array<_BookFormat>;
} {
    return {
        id: value.id,
        coverImageUrl: value.coverImageUrl,
        title: value.title,
        featured: value.featured,
        audiobookLink: value.audiobookLink ? candid_some(value.audiobookLink) : candid_none(),
        description: value.description,
        genre: value.genre,
        formats: to_candid_vec_n10(_uploadFile, _downloadFile, value.formats)
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "paperback";
    paperback: string;
} | {
    __kind__: "kindle";
    kindle: string;
}): {
    paperback: string;
} | {
    kindle: string;
} {
    return value.__kind__ === "paperback" ? {
        paperback: value.paperback
    } : value.__kind__ === "kindle" ? {
        kindle: value.kindle
    } : value;
}
function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<BookFormat>): Array<_BookFormat> {
    return value.map((x)=>to_candid_BookFormat_n11(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
